repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.6
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
    - id: mypy
      args: ["--install-types", "--non-interactive"]
      # Используем только самые необходимые типы вместо types-all
      additional_dependencies:
        - types-aiofiles
        - types-PyYAML
        - types-dateparser
        - types-pytz
        - types-setuptools

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
    - id: bandit
      additional_dependencies: [pbr]
      args: [--ini, .bandit.ini]